language: java
jdk:
- oraclejdk8
sudo: true
addons:
  mariadb: '10.0'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq sphinxsearch
- ./install/install.sh
before_script:
- mysql -uroot < srvlog-sql/db/create_srvlog_db.sql
- sudo cp srvlog-it/travis/mariadb/my.cnf /etc/mysql/my.cnf
- sudo service mysql restart
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=vzarubin-github -Dsonar.login=cd26497501e4c4a6829c9109141a7fc8d378d6b8 -Pintegration-test
