language: java
jdk:
- oraclejdk8
sudo: true
addons:
  mariadb: '10.0'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq sphinxsearch
- sudo bash ./srvlog/install/install.sh
before_script:
- mysql -uroot < ./srvlog/srvlog-sql/db/create_srvlog_db.sql
script: cd srvlog && mvn clean install -Pintegration-test
